kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${APP_NAME}
  annotations:
    description: Agent émetteur Aries supportant la révocation basé sur Aries Cloud Agent Python (ACA-Py).
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
      app.openshift.io/route-disabled: "false"
    labels:
      app: pgadmin4
      app.kubernetes.io/component: pgadmin4
      app.kubernetes.io/instance: pgadmin4
      app.kubernetes.io/name: pgadmin4
      app.kubernetes.io/part-of: issuer-port-e
      app.openshift.io/runtime: pgadmin4
      app.openshift.io/runtime-namespace: exp-port-e-2
      app.openshift.io/runtime-version: latest
    name: pgadmin4
    namespace: exp-port-e-2
  spec:
    selector:
      app: pgadmin4
      deploymentconfig: pgadmin4
    strategy:
        type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          app: pgadmin4
          deploymentconfig: pgadmin4
      spec:
        containers:
        - name: pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@todo.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: todo
          image: "dpage/pgadmin4:6.15"
          imagePullPolicy: IfNotPresent
          name: pgadmin4
          ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/pgadmin
            name: pgadmin4-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: pgadmin4-1
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - pgadmin4
        from:
          kind: ImageStreamTag
          name: pgadmin4:6.15
          namespace: exp-port-e-2
        lastTriggeredImage: ''
      type: ImageChange
    - type: ConfigChange
