@startuml ArchitectureGlobal
agent "RFID Reader" as reader
agent "M Controller" as controller
agent ESP8266
agent Keycloak
agent "http://" as URL
agent "Access Denied" as Denied
agent "Ressource protegé" as Protege
agent Realm
agent "Vérificateur /  ACA-Py" as Verif
cloud Internet
agent Emetteur
actor "Gestionnaire d'accès" as Gestionnaire
agent "Création du profil usager" as CProfile
agent Invite
agent Invitation
agent Boite
agent DB
    

'Références graphique
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist

'Composants graphique
!includeurl AWSPuml/AWSSimplified.puml
!includeurl AWSPuml/General/MobileClient.puml
!includeurl AWSPuml/Blockchain/Blockchain.puml

'left to right direction

MobileClient(cellCA, "Portefeuille numérique", "appareil de l'employé") #LightBlue
Blockchain(dltCA, "Blockchain CANdy", "Registre de confiance") #LightBlue

'**************
'DÉFINITION DES LIENS
'**************

'LIENS DU TOP DU DIAGRAMME
    cellCA --> reader : "Présente token"
    reader --> cellCA : "Demande token"
    reader -- controller
    controller -- ESP8266
    ESP8266 -- Internet


'LIENS DU CENTRE DU DIAGRAMME
cellCA --> Keycloak : "Présente preuve"
Keycloak --> cellCA : "Demande preuve"
URL --> Keycloak
Keycloak --> Denied
Keycloak <--> Protege
Keycloak <--> Realm
Keycloak <--> Verif

'LIENS DU DROIT DU DIAGRAMME
Verif --> dltCA
Internet --> Verif : "Journalisation accès physique?"

'LIENS DU BAS DU DIAGRAMME
dltCA <--> cellCA
Emetteur <--> Verif
Emetteur --> Invitation
Invitation --> Boite
Boite --> cellCA
Emetteur --> DB
Gestionnaire --> CProfile
CProfile --> Invite
Invite --> Emetteur
CProfile --> DB
@enduml