@startuml ArchitectureGlobal
agent "RFID Reader" as reader
agent "M Controller" as controller
agent ESP8266
agent Keycloak
agent "http://" as URL
agent "Access Denied" as Denied
agent "Ressource protegé" as Protege
agent Realm
agent "Vérificateur /  ACA-Py" as Verif
cloud Internet

'Références graphique
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist

'Composants graphique
!includeurl AWSPuml/AWSSimplified.puml
!includeurl AWSPuml/General/MobileClient.puml
!includeurl AWSPuml/Blockchain/Blockchain.puml

left to right direction

MobileClient(cellCA, "Portefeuille numérique", "appareil de l'employé") #LightBlue
Blockchain(dltCA, "Blockchain CANdy", "Registre de confiance") #LightBlue

'**************
'DÉFINITION DES LIENS
'**************

cellCA --> reader : "Présente token"
reader --> cellCA : "Demande token"
reader -- controller
controller -- ESP8266
ESP8266 -- Internet


cellCA --> Keycloak : "Présente preuve"
Keycloak --> cellCA : "Demande preuve"
URL --> Keycloak
Keycloak --> Denied
Keycloak <--> Protege
Keycloak <--> Realm
Keycloak <--> Verif
Verif --> dltCA
Internet --> Verif : "Journalisation accès physique?"

@enduml