@startuml SchemaConsommteurPhysique
autonumber

'*************
'Déclaration de participants
'*************
actor Employé as Employee #Blue
participant  "Portefeuille \nNumérique" as Wallet
participant "NFC \nReader" as Reader
participant "ESP8266 \nMicroController" as ESP8266
participant "Vérificateur \nACA-Py" as ACAPY   
collections CANdy
database Journal #Orange

'**************
'DÉFINITION DES LIENS
'**************
Employee -> Wallet : Ouvrir Port-E
Reader -> Wallet : Demande token
Wallet -> Reader :  Présente token
Reader -> ESP8266 : Demande attestation d'accès
ESP8266 -> ACAPY : Demande attestation d'accès
ACAPY -> Wallet : Demande preuve d'attestation d'accès
Wallet -> CANdy : Présente preuve d'attestation d'accès
CANdy -> ESP8266 : Présente preuve d'attestation d'accès
ESP8266 -> Employee : Ouvre la porte
ESP8266 -> Journal : Log 

@enduml