@startuml SchemaConsommteurVirtuel
autonumber

'*************
'Déclaration de participants
'*************
actor Employé as Employee #Blue
participant Keycloak
participant Realm
participant "Vérificateur \nACA-Py" as ACAPY   
participant  "Portefeuille \nNumérique" as Wallet
collections CANdy
    

'**************
'DÉFINITION DES LIENS
'**************
Employee -> Keycloak : Saisir site web
Keycloak -> Realm : Demander stratégie d'authentification
Keycloak -> ACAPY : Demande preuve d'attestation d'accès
ACAPY -> Wallet : Demande preuve d'attestation d'accès
Wallet -> CANdy : Présente preuve d'attestation d'accès
CANdy -> Keycloak : Présente preuve d'attestation d'accès
Keycloak -> Employee : Donner accès
@enduml