@startuml SchemaEmetteur
autonumber

'*************
'Déclaration de participants
'*************
actor "Gestionnaire \nd'accès" as Gestionnaire
database "DB" as DB #LightBlue
actor Employé as Employee
participant Émetteur as Emetteur
participant "Boîte eMail" as Boite
participant  "Portefeuille \nNumérique" as wallet    
participant "Agent mediateur" as AM
participant "ACA-Py" as ACAPY   
collections CANdy
'**************
'DÉFINITION DES LIENS
'**************
Gestionnaire -> DB : Création du profil usager
Gestionnaire -> DB : Donner accès
Employee -> Emetteur : Saisir courriel
Emetteur <-> ACAPY : Demander lien d'invitation
'Emetteur <-> DB : Vérification de l'accès
Emetteur -> Boite : Envoyer lien à utilisation unique
Employee -> Boite : Lire courriel et clic sur lien unique
Boite -> Employee : Affichage du code QR
wallet -> Employee : Lecture du code QR
wallet -> AM : Demande attestation d'accès
AM -> ACAPY : Demande attestation d'accès
ACAPY -> CANdy : Demande attestation d'accès
CANdy -> wallet : Réception de l'attestation

@enduml