@startuml

'**************
'PROCESSUS DE VÉRIFICATION
'**************
caption "Posséder l'accès"
actor "Employé" as empl
actor "Administrateur d'accès" as admin
agent "Donner accès" as donne
agent "Télécharger App Porte:E" as app
agent "Recevoir courriel de vérification" as verif
agent "Lire code QR" as scan
agent "Autodemander invitation" as autodemande

admin --> donne
donne -|> autodemande
empl --> app
app --> autodemande
autodemande --> verif
verif --> scan
scan --> fin
@enduml